#### 1. 划分数据集

In [76]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split  
import pandas as pd
#分块处理大文件
# chunk_iter = pd.read_csv("data/train_data.csv", chunksize=10000)
# chunks = [chunk for chunk in chunk_iter]
# train_data = pd.concat(chunks)
train_data = pd.read_csv("train/train.csv")
test_data = pd.read_csv("testaa/testaa.csv")
'''
train_data = train_data.drop(columns='issueDate')
test_data = test_data.drop(columns='issueDate')
'''
'''#截取前10000行数据
train_data=train_data.iloc[:10000,2:] '''
'''
# 划分特征变量与目标变量
X=train_data.drop(columns='isDefault')
Y=train_data['isDefault']
# 划分训练及测试集
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)
'''

train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53480 entries, 0 to 53479
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                53480 non-null  int64
 1   title             53480 non-null  int64
 2   career            50872 non-null  float64
 3   zip_code          53480 non-null  int64
 4   residence         53480 non-null  int64
 5   loan              53480 non-null  int64
 6   term              53480 non-null  int64
 7   interest_rate     53480 non-null  float64
 8   issue_time        53480 non-null  int64
 9   syndicated        53480 non-null  int64
 10  installment       53480 non-null  int64
 11  record_time       53480 non-null  int64
 12  history_time      53480 non-null  int64
 13  total_accounts    53480 non-null  float64
 14  balance_accounts  53480 non-null  float64
 15  balance_limit     53350 non-null  float64
 16  balance           53480 non-null  float64
 17  level             53480 non-null  object
 18  label             53480 non-null  int64
dtypes: float64(6), int64(12), object(1)
memory usage: 7.8+ MB

In [77]:
###   特征工程
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# 1. 删除id列（正确用法）
train_data.drop('id', axis=1, inplace=True)  # 不赋值，直接修改原对象
# 删除zip-code
train_data.drop('zip_code',axis=1, inplace=True)
test_data.drop('zip_code',axis=1, inplace=True)

# 2. 分离特征类型
# 1. 初始自动分离（基于数据类型）
numerical_fea = train_data.select_dtypes(exclude=['object']).columns.tolist()
category_fea = train_data.select_dtypes(include=['object']).columns.tolist()
numerical_fea.remove('label')  # 移除标签列

# 2. 手动调整特定字段类型
features_to_convert = ['title', 'career','residence']  # 需重分类的特征

# 将指定特征从类别型移至数值型
for feature in features_to_convert:
    if feature in category_fea:
        category_fea.remove(feature)
        numerical_fea.append(feature)

# 3. 缺失值处理
# 数值特征：中位数填充 balance_limit
train_data[numerical_fea] = train_data[numerical_fea].fillna(train_data[numerical_fea].median())
test_data[numerical_fea] = test_data[numerical_fea].fillna(test_data[numerical_fea].median())
# 类别特征：众数填充/-1填充 career
train_data[category_fea] = train_data[category_fea].fillna(-1)
test_data[category_fea] = test_data[category_fea].fillna(-1)
'''
imputer = SimpleImputer(strategy='most_frequent')
train_data[category_fea] = imputer.fit_transform(train_data[category_fea])
test_data[category_fea] = imputer.fit_transform(test_data[category_fea])
'''

# 4. 类别特征编码
def level_to_num(level):
    grade_map = {'A':0, 'B':1, 'C':2, 'D':3, 'E':4}
    grade = level[0]              # A/B/C/D/E
    sub = int(level[1])           # 0-5
    return grade_map[grade] * 6 + sub
train_data['level_num'] = train_data['level'].apply(level_to_num)
test_data['level_num'] = test_data['level'].apply(level_to_num)
train_data.drop('level', axis=1, inplace=True)
test_data.drop('level', axis=1, inplace=True)
numerical_fea.append('level_num')
category_fea.remove('level')


'''
# 5. 数值特征标准化
scaler = StandardScaler()
train_data[numerical_fea] = scaler.fit_transform(train_data[numerical_fea])
'''

'\n# 5. 数值特征标准化\nscaler = StandardScaler()\ntrain_data[numerical_fea] = scaler.fit_transform(train_data[numerical_fea])\n'

In [78]:
# 对时间进行处理
import datetime
current_time = datetime.datetime.now()  # 或定义一个基准时间
original_time = ['issue_time', 'record_time', 'history_time']
for time_col in original_time:
    train_data[time_col + '_dt'] = pd.to_datetime(train_data[time_col], unit='s')  # Unix秒时间戳
    test_data[time_col + '_dt'] = pd.to_datetime(test_data[time_col], unit='s')
    train_data[time_col + '_age_days'] = (current_time - train_data[time_col + '_dt']).dt.days
    test_data[time_col + '_age_days'] = (current_time - test_data[time_col + '_dt']).dt.days
    numerical_fea.remove(time_col)
    numerical_fea.append(time_col + '_age_days')
    train_data.drop(time_col + '_dt',axis=1, inplace=True)
    test_data.drop(time_col + '_dt',axis=1, inplace=True)


train_data.drop(original_time,axis=1, inplace=True)
test_data.drop(original_time,axis=1, inplace=True)

#cat feature处理
catfeature_list = [col for col in train_data.columns if col != "label"]
for fea in catfeature_list:
    train_data[fea] = train_data[fea].astype('int64')
    test_data[fea] = test_data[fea].astype('int64')

In [ ]:
'''
#新特征
train_data['utilization_ratio'] = train_data['balance'] / (train_data['balance_limit'] + 1e-6)  # 避免除0
train_data['active_account_ratio'] = train_data['balance_accounts'] / (train_data['total_accounts'] + 1e-6)  # 避免除0
train_data['available_credit'] = train_data['balance_limit'] - train_data['balance']
test_data['utilization_ratio'] = test_data['balance'] / (test_data['balance_limit'] + 1e-6)  # 避免除0
test_data['active_account_ratio'] = test_data['balance_accounts'] / (test_data['total_accounts'] + 1e-6)  # 避免除0
test_data['available_credit'] = test_data['balance_limit'] - test_data['balance']
'''

In [62]:
category_fea

[]

In [63]:
numerical_fea

['title',
 'career',
 'residence',
 'loan',
 'term',
 'interest_rate',
 'issue_time',
 'syndicated',
 'installment',
 'record_time',
 'history_time',
 'total_accounts',
 'balance_accounts',
 'balance_limit',
 'balance',
 'level_num']

In [65]:
catfeature_list

['title',
 'career',
 'residence',
 'loan',
 'term',
 'interest_rate',
 'syndicated',
 'installment',
 'total_accounts',
 'balance_accounts',
 'balance_limit',
 'balance',
 'level_num',
 'issue_time_age_days',
 'record_time_age_days',
 'history_time_age_days']

In [72]:
train_data.head()

,title,career,residence,loan,term,interest_rate,syndicated,installment,total_accounts,balance_accounts,balance_limit,balance,label,level_num,issue_time_age_days,record_time_age_days,history_time_age_days,utilization_ratio,active_account_ratio,available_credit
0,9,0,1,7200,36,10,0,1,17,9,36200,13856,0,4,5991,5991,14864,0.382762,0.529412,22344
1,8,10,0,21300,36,12,0,0,17,9,20400,13773,1,6,7269,6879,11487,0.675147,0.529412,6627
2,8,7,1,10400,60,21,0,0,17,9,10800,2023,0,10,5869,4309,11911,0.187315,0.529412,8777
3,7,2,0,33050,36,16,0,1,17,9,24700,21992,0,9,6752,6272,12368,0.890364,0.529412,2708
4,8,3,1,5200,36,14,0,0,17,9,5100,1669,1,8,6752,5972,16600,0.327255,0.529412,3431

In [79]:
from sklearn.model_selection import train_test_split
feature_list = [col for col in train_data.columns if col != "label"]
X_train, X_validation, y_train, y_validation = train_test_split(train_data.loc[:, feature_list], train_data.loc[:, 'label'], test_size=0.2 , random_state=2000)

In [44]:
X_train.head()

,title,career,residence,loan,term,interest_rate,syndicated,installment,total_accounts,balance_accounts,balance_limit,balance,level_num,issue_time_age_days,record_time_age_days,history_time_age_days,utilization_ratio,active_account_ratio,available_credit
12232,7,10,0,5200,36,9,0,1,41,15,29800,13698,3,6721,6721,11456,0.459664,0.365854,16102
12974,6,-1,0,33050,36,19,0,0,15,8,53600,45655,10,6691,6691,15412,0.851772,0.533333,7945
47946,1,4,1,11000,12,30,0,0,10,6,6878,3776,3,6824,7250,8421,0.548997,0.600000,3102
6185,9,7,1,15350,36,13,0,0,43,17,15200,8884,7,6022,5512,11334,0.584474,0.395349,6316
29067,0,4,2,9000,12,10,0,0,5,2,1904,1546,6,6883,7084,8206,0.811975,0.400000,358

In [80]:
# 3. 模型建立与训练
# 确保 Notebook 内联显示图形
%matplotlib inline 
from catboost import CatBoostClassifier

model = CatBoostClassifier(iterations=2000,
                           task_type='CPU',
                           cat_features=catfeature_list,
                           eval_metric='AUC',
                           logging_level='Verbose',
                           learning_rate=0.03,
                           depth=6, 
                           l2_leaf_reg=5,
                           loss_function='Logloss',
                            early_stopping_rounds=300,
                           scale_pos_weight=(len(y_train[y_train==0])/len(y_train[y_train == 1])))
'''
model = CatBoostClassifier(iterations=5000,
                           cat_features=feature_list,
                           eval_metric='AUC',
                           logging_level='Verbose',
                           learning_rate=0.01,
                           depth=6, l2_leaf_reg=5,
                           loss_function='CrossEntropy')
                           '''
model.fit(X_train.loc[:, feature_list], y_train, 
          eval_set=(X_validation.loc[:, feature_list], y_validation), plot=True)

plt.show()

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	test: 0.6178692	best: 0.6178692 (0)	total: 118ms	remaining: 3m 56s
1:	test: 0.6181469	best: 0.6181469 (1)	total: 207ms	remaining: 3m 26s
2:	test: 0.6200003	best: 0.6200003 (2)	total: 403ms	remaining: 4m 28s
3:	test: 0.6193857	best: 0.6200003 (2)	total: 509ms	remaining: 4m 13s
4:	test: 0.6195619	best: 0.6200003 (2)	total: 618ms	remaining: 4m 6s
5:	test: 0.6210722	best: 0.6210722 (5)	total: 750ms	remaining: 4m 9s
6:	test: 0.6209612	best: 0.6210722 (5)	total: 844ms	remaining: 4m
7:	test: 0.6233285	best: 0.6233285 (7)	total: 1.08s	remaining: 4m 30s
8:	test: 0.6261137	best: 0.6261137 (8)	total: 1.17s	remaining: 4m 19s
9:	test: 0.6234857	best: 0.6261137 (8)	total: 1.27s	remaining: 4m 11s
10:	test: 0.6251790	best: 0.6261137 (8)	total: 1.41s	remaining: 4m 14s
11:	test: 0.6252784	best: 0.6261137 (8)	total: 1.5s	remaining: 4m 8s
12:	test: 0.6266249	best: 0.6266249 (12)	total: 1.6s	remaining: 4m 4s
13:	test: 0.6285637	best: 0.6285637 (13)	total: 1.66s	remaining: 3m 56s
14:	test: 0.6279505	best: 0.6285637 (13)	total: 1.73s	remaining: 3m 49s
15:	test: 0.6287056	best: 0.6287056 (15)	total: 1.89s	remaining: 3m 54s
16:	test: 0.6285612	best: 0.6287056 (15)	total: 1.99s	remaining: 3m 52s
17:	test: 0.6289212	best: 0.6289212 (17)	total: 2.1s	remaining: 3m 51s
18:	test: 0.6293436	best: 0.6293436 (18)	total: 2.19s	remaining: 3m 48s
19:	test: 0.6304146	best: 0.6304146 (19)	total: 2.28s	remaining: 3m 45s
20:	test: 0.6305068	best: 0.6305068 (20)	total: 2.36s	remaining: 3m 42s
21:	test: 0.6302615	best: 0.6305068 (20)	total: 2.45s	remaining: 3m 40s
22:	test: 0.6297719	best: 0.6305068 (20)	total: 2.53s	remaining: 3m 37s
23:	test: 0.6297768	best: 0.6305068 (20)	total: 2.65s	remaining: 3m 38s
24:	test: 0.6300263	best: 0.6305068 (20)	total: 2.75s	remaining: 3m 37s
25:	test: 0.6301259	best: 0.6305068 (20)	total: 2.81s	remaining: 3m 33s
26:	test: 0.6301652	best: 0.6305068 (20)	total: 2.9s	remaining: 3m 32s
27:	test: 0.6298392	best: 0.6305068 (20)	total: 2.99s	remaining: 3m 30s
28:	test: 0.6304126	best: 0.6305068 (20)	total: 3.07s	remaining: 3m 28s
29:	test: 0.6302720	best: 0.6305068 (20)	total: 3.2s	remaining: 3m 30s
30:	test: 0.6299779	best: 0.6305068 (20)	total: 3.3s	remaining: 3m 29s
31:	test: 0.6292357	best: 0.6305068 (20)	total: 3.38s	remaining: 3m 28s
32:	test: 0.6294877	best: 0.6305068 (20)	total: 3.47s	remaining: 3m 26s
33:	test: 0.6292529	best: 0.6305068 (20)	total: 3.53s	remaining: 3m 24s
34:	test: 0.6297245	best: 0.6305068 (20)	total: 3.6s	remaining: 3m 22s
35:	test: 0.6293977	best: 0.6305068 (20)	total: 3.67s	remaining: 3m 20s
36:	test: 0.6298106	best: 0.6305068 (20)	total: 3.77s	remaining: 3m 20s
37:	test: 0.6347725	best: 0.6347725 (37)	total: 3.85s	remaining: 3m 18s
38:	test: 0.6383577	best: 0.6383577 (38)	total: 3.93s	remaining: 3m 17s
39:	test: 0.6403244	best: 0.6403244 (39)	total: 4.01s	remaining: 3m 16s
40:	test: 0.6421405	best: 0.6421405 (40)	total: 4.08s	remaining: 3m 14s
41:	test: 0.6427150	best: 0.6427150 (41)	total: 4.16s	remaining: 3m 13s
42:	test: 0.6426688	best: 0.6427150 (41)	total: 4.24s	remaining: 3m 12s
43:	test: 0.6426797	best: 0.6427150 (41)	total: 4.32s	remaining: 3m 12s
44:	test: 0.6431023	best: 0.6431023 (44)	total: 4.42s	remaining: 3m 11s
45:	test: 0.6434711	best: 0.6434711 (45)	total: 4.48s	remaining: 3m 10s
46:	test: 0.6437488	best: 0.6437488 (46)	total: 4.55s	remaining: 3m 8s
47:	test: 0.6438776	best: 0.6438776 (47)	total: 4.62s	remaining: 3m 7s
48:	test: 0.6440862	best: 0.6440862 (48)	total: 4.71s	remaining: 3m 7s
49:	test: 0.6446194	best: 0.6446194 (49)	total: 4.78s	remaining: 3m 6s
50:	test: 0.6446488	best: 0.6446488 (50)	total: 4.86s	remaining: 3m 5s
51:	test: 0.6445736	best: 0.6446488 (50)	total: 4.93s	remaining: 3m 4s
52:	test: 0.6445935	best: 0.6446488 (50)	total: 5s	remaining: 3m 3s
53:	test: 0.6447499	best: 0.6447499 (53)	total: 5.07s	remaining: 3m 2s
54:	test: 0.6448303	best: 0.6448303 (54)	total: 5.14s	remaining: 3m 1s
55:	test: 0.6448719	best: 0.6448719 (55)	total: 5.22s	remaining: 3m 1s
56:	test: 0.6447933	best: 0.6448719 (55)	total: 5.3s	remaining: 3m
57:	test: 0.6452823	best: 0.6452823 (57)	total: 5.39s	remaining: 3m
58:	test: 0.6454429	best: 0.6454429 (58)	total: 5.5s	remaining: 3m
59:	test: 0.6457677	best: 0.6457677 (59)	total: 5.6s	remaining: 3m
60:	test: 0.6456718	best: 0.6457677 (59)	total: 5.68s	remaining: 3m
61:	test: 0.6458769	best: 0.6458769 (61)	total: 5.77s	remaining: 3m
62:	test: 0.6458824	best: 0.6458824 (62)	total: 5.79s	remaining: 2m 58s
63:	test: 0.6457635	best: 0.6458824 (62)	total: 5.87s	remaining: 2m 57s
64:	test: 0.6461117	best: 0.6461117 (64)	total: 5.95s	remaining: 2m 57s
65:	test: 0.6467710	best: 0.6467710 (65)	total: 6.03s	remaining: 2m 56s
66:	test: 0.6470807	best: 0.6470807 (66)	total: 6.1s	remaining: 2m 56s
67:	test: 0.6477397	best: 0.6477397 (67)	total: 6.18s	remaining: 2m 55s
68:	test: 0.6480030	best: 0.6480030 (68)	total: 6.23s	remaining: 2m 54s
69:	test: 0.6481922	best: 0.6481922 (69)	total: 6.3s	remaining: 2m 53s
70:	test: 0.6480301	best: 0.6481922 (69)	total: 6.37s	remaining: 2m 53s
71:	test: 0.6479692	best: 0.6481922 (69)	total: 6.45s	remaining: 2m 52s
72:	test: 0.6484886	best: 0.6484886 (72)	total: 6.53s	remaining: 2m 52s
73:	test: 0.6483491	best: 0.6484886 (72)	total: 6.61s	remaining: 2m 52s
74:	test: 0.6484411	best: 0.6484886 (72)	total: 6.69s	remaining: 2m 51s
75:	test: 0.6486242	best: 0.6486242 (75)	total: 6.78s	remaining: 2m 51s
76:	test: 0.6487001	best: 0.6487001 (76)	total: 6.86s	remaining: 2m 51s
77:	test: 0.6486320	best: 0.6487001 (76)	total: 6.92s	remaining: 2m 50s
78:	test: 0.6486017	best: 0.6487001 (76)	total: 6.99s	remaining: 2m 49s
79:	test: 0.6485939	best: 0.6487001 (76)	total: 7.08s	remaining: 2m 49s
80:	test: 0.6487259	best: 0.6487259 (80)	total: 7.15s	remaining: 2m 49s
81:	test: 0.6488984	best: 0.6488984 (81)	total: 7.23s	remaining: 2m 49s
82:	test: 0.6489184	best: 0.6489184 (82)	total: 7.31s	remaining: 2m 48s
83:	test: 0.6489365	best: 0.6489365 (83)	total: 7.41s	remaining: 2m 49s
84:	test: 0.6488503	best: 0.6489365 (83)	total: 7.5s	remaining: 2m 49s
85:	test: 0.6488460	best: 0.6489365 (83)	total: 7.57s	remaining: 2m 48s
86:	test: 0.6488614	best: 0.6489365 (83)	total: 7.65s	remaining: 2m 48s
87:	test: 0.6488577	best: 0.6489365 (83)	total: 7.69s	remaining: 2m 47s
88:	test: 0.6488985	best: 0.6489365 (83)	total: 8.07s	remaining: 2m 53s
89:	test: 0.6488320	best: 0.6489365 (83)	total: 8.14s	remaining: 2m 52s
90:	test: 0.6489863	best: 0.6489863 (90)	total: 8.22s	remaining: 2m 52s
91:	test: 0.6488105	best: 0.6489863 (90)	total: 8.32s	remaining: 2m 52s
92:	test: 0.6490891	best: 0.6490891 (92)	total: 8.49s	remaining: 2m 54s
93:	test: 0.6494606	best: 0.6494606 (93)	total: 8.58s	remaining: 2m 54s
94:	test: 0.6494937	best: 0.6494937 (94)	total: 8.67s	remaining: 2m 53s
95:	test: 0.6495857	best: 0.6495857 (95)	total: 8.74s	remaining: 2m 53s
96:	test: 0.6497658	best: 0.6497658 (96)	total: 8.83s	remaining: 2m 53s
97:	test: 0.6499147	best: 0.6499147 (97)	total: 8.9s	remaining: 2m 52s
98:	test: 0.6499704	best: 0.6499704 (98)	total: 8.98s	remaining: 2m 52s
99:	test: 0.6501408	best: 0.6501408 (99)	total: 9.07s	remaining: 2m 52s
100:	test: 0.6500458	best: 0.6501408 (99)	total: 9.15s	remaining: 2m 52s
101:	test: 0.6500383	best: 0.6501408 (99)	total: 9.21s	remaining: 2m 51s
102:	test: 0.6500732	best: 0.6501408 (99)	total: 9.29s	remaining: 2m 51s
103:	test: 0.6500535	best: 0.6501408 (99)	total: 9.38s	remaining: 2m 50s
104:	test: 0.6500379	best: 0.6501408 (99)	total: 9.45s	remaining: 2m 50s
105:	test: 0.6501134	best: 0.6501408 (99)	total: 9.54s	remaining: 2m 50s
106:	test: 0.6501325	best: 0.6501408 (99)	total: 9.63s	remaining: 2m 50s
107:	test: 0.6501660	best: 0.6501660 (107)	total: 9.73s	remaining: 2m 50s
108:	test: 0.6503430	best: 0.6503430 (108)	total: 9.85s	remaining: 2m 50s
109:	test: 0.6503270	best: 0.6503430 (108)	total: 9.98s	remaining: 2m 51s
110:	test: 0.6502731	best: 0.6503430 (108)	total: 10.1s	remaining: 2m 52s
111:	test: 0.6502146	best: 0.6503430 (108)	total: 10.2s	remaining: 2m 51s
112:	test: 0.6502661	best: 0.6503430 (108)	total: 10.3s	remaining: 2m 51s
113:	test: 0.6503601	best: 0.6503601 (113)	total: 10.3s	remaining: 2m 51s
114:	test: 0.6505325	best: 0.6505325 (114)	total: 10.4s	remaining: 2m 50s
115:	test: 0.6507006	best: 0.6507006 (115)	total: 10.5s	remaining: 2m 50s
116:	test: 0.6507520	best: 0.6507520 (116)	total: 10.6s	remaining: 2m 49s
117:	test: 0.6508581	best: 0.6508581 (117)	total: 10.6s	remaining: 2m 49s
118:	test: 0.6511492	best: 0.6511492 (118)	total: 10.7s	remaining: 2m 49s
119:	test: 0.6511537	best: 0.6511537 (119)	total: 10.8s	remaining: 2m 49s
120:	test: 0.6511178	best: 0.6511537 (119)	total: 10.9s	remaining: 2m 48s
121:	test: 0.6511249	best: 0.6511537 (119)	total: 11s	remaining: 2m 48s
122:	test: 0.6512755	best: 0.6512755 (122)	total: 11s	remaining: 2m 48s
123:	test: 0.6512487	best: 0.6512755 (122)	total: 11.1s	remaining: 2m 48s
124:	test: 0.6513213	best: 0.6513213 (124)	total: 11.2s	remaining: 2m 47s
125:	test: 0.6515962	best: 0.6515962 (125)	total: 11.3s	remaining: 2m 47s
126:	test: 0.6517106	best: 0.6517106 (126)	total: 11.3s	remaining: 2m 47s
127:	test: 0.6517989	best: 0.6517989 (127)	total: 11.4s	remaining: 2m 47s
128:	test: 0.6516819	best: 0.6517989 (127)	total: 11.5s	remaining: 2m 47s
129:	test: 0.6517404	best: 0.6517989 (127)	total: 11.6s	remaining: 2m 46s
130:	test: 0.6517973	best: 0.6517989 (127)	total: 11.7s	remaining: 2m 47s
131:	test: 0.6517404	best: 0.6517989 (127)	total: 11.8s	remaining: 2m 46s
132:	test: 0.6516809	best: 0.6517989 (127)	total: 11.9s	remaining: 2m 46s
133:	test: 0.6517122	best: 0.6517989 (127)	total: 12s	remaining: 2m 46s
134:	test: 0.6517771	best: 0.6517989 (127)	total: 12s	remaining: 2m 46s
135:	test: 0.6518500	best: 0.6518500 (135)	total: 12.1s	remaining: 2m 45s
136:	test: 0.6518094	best: 0.6518500 (135)	total: 12.2s	remaining: 2m 45s
137:	test: 0.6518752	best: 0.6518752 (137)	total: 12.3s	remaining: 2m 45s
138:	test: 0.6519054	best: 0.6519054 (138)	total: 12.4s	remaining: 2m 45s
139:	test: 0.6519211	best: 0.6519211 (139)	total: 12.5s	remaining: 2m 45s
140:	test: 0.6519422	best: 0.6519422 (140)	total: 12.5s	remaining: 2m 45s
141:	test: 0.6518671	best: 0.6519422 (140)	total: 12.6s	remaining: 2m 45s
142:	test: 0.6519027	best: 0.6519422 (140)	total: 12.7s	remaining: 2m 45s
143:	test: 0.6518716	best: 0.6519422 (140)	total: 12.8s	remaining: 2m 44s
144:	test: 0.6517496	best: 0.6519422 (140)	total: 12.9s	remaining: 2m 44s
145:	test: 0.6517406	best: 0.6519422 (140)	total: 13s	remaining: 2m 44s
146:	test: 0.6521157	best: 0.6521157 (146)	total: 13.1s	remaining: 2m 44s
147:	test: 0.6521000	best: 0.6521157 (146)	total: 13.2s	remaining: 2m 45s
148:	test: 0.6521451	best: 0.6521451 (148)	total: 13.3s	remaining: 2m 44s
149:	test: 0.6521540	best: 0.6521540 (149)	total: 13.4s	remaining: 2m 44s
150:	test: 0.6521096	best: 0.6521540 (149)	total: 13.5s	remaining: 2m 44s
151:	test: 0.6520911	best: 0.6521540 (149)	total: 13.5s	remaining: 2m 44s
152:	test: 0.6520352	best: 0.6521540 (149)	total: 13.6s	remaining: 2m 43s
153:	test: 0.6519506	best: 0.6521540 (149)	total: 13.7s	remaining: 2m 43s
154:	test: 0.6519234	best: 0.6521540 (149)	total: 13.7s	remaining: 2m 43s
155:	test: 0.6518804	best: 0.6521540 (149)	total: 13.8s	remaining: 2m 43s
156:	test: 0.6518852	best: 0.6521540 (149)	total: 13.9s	remaining: 2m 43s
157:	test: 0.6519208	best: 0.6521540 (149)	total: 14s	remaining: 2m 43s
158:	test: 0.6519258	best: 0.6521540 (149)	total: 14.1s	remaining: 2m 42s
159:	test: 0.6519843	best: 0.6521540 (149)	total: 14.2s	remaining: 2m 42s
160:	test: 0.6519756	best: 0.6521540 (149)	total: 14.2s	remaining: 2m 42s
161:	test: 0.6520007	best: 0.6521540 (149)	total: 14.3s	remaining: 2m 42s
162:	test: 0.6520412	best: 0.6521540 (149)	total: 14.4s	remaining: 2m 42s
163:	test: 0.6520618	best: 0.6521540 (149)	total: 14.5s	remaining: 2m 42s
164:	test: 0.6521652	best: 0.6521652 (164)	total: 14.6s	remaining: 2m 42s
165:	test: 0.6522629	best: 0.6522629 (165)	total: 14.7s	remaining: 2m 42s
166:	test: 0.6523376	best: 0.6523376 (166)	total: 14.8s	remaining: 2m 42s
167:	test: 0.6523419	best: 0.6523419 (167)	total: 14.9s	remaining: 2m 42s
168:	test: 0.6523244	best: 0.6523419 (167)	total: 15s	remaining: 2m 42s
169:	test: 0.6522832	best: 0.6523419 (167)	total: 15.1s	remaining: 2m 42s
170:	test: 0.6522791	best: 0.6523419 (167)	total: 15.1s	remaining: 2m 41s
171:	test: 0.6522756	best: 0.6523419 (167)	total: 15.2s	remaining: 2m 41s
172:	test: 0.6521867	best: 0.6523419 (167)	total: 15.3s	remaining: 2m 41s
173:	test: 0.6521812	best: 0.6523419 (167)	total: 15.4s	remaining: 2m 41s
174:	test: 0.6522875	best: 0.6523419 (167)	total: 15.5s	remaining: 2m 42s
175:	test: 0.6522831	best: 0.6523419 (167)	total: 15.6s	remaining: 2m 41s
176:	test: 0.6521949	best: 0.6523419 (167)	total: 15.7s	remaining: 2m 41s
177:	test: 0.6522103	best: 0.6523419 (167)	total: 15.8s	remaining: 2m 41s
178:	test: 0.6524100	best: 0.6524100 (178)	total: 15.9s	remaining: 2m 41s
179:	test: 0.6523866	best: 0.6524100 (178)	total: 16s	remaining: 2m 41s
180:	test: 0.6523661	best: 0.6524100 (178)	total: 16s	remaining: 2m 41s
181:	test: 0.6523448	best: 0.6524100 (178)	total: 16.1s	remaining: 2m 41s
182:	test: 0.6524744	best: 0.6524744 (182)	total: 16.2s	remaining: 2m 40s
183:	test: 0.6524475	best: 0.6524744 (182)	total: 16.3s	remaining: 2m 40s
184:	test: 0.6523408	best: 0.6524744 (182)	total: 16.4s	remaining: 2m 40s
185:	test: 0.6523850	best: 0.6524744 (182)	total: 16.5s	remaining: 2m 40s
186:	test: 0.6524364	best: 0.6524744 (182)	total: 16.6s	remaining: 2m 40s
187:	test: 0.6524755	best: 0.6524755 (187)	total: 16.7s	remaining: 2m 40s
188:	test: 0.6524826	best: 0.6524826 (188)	total: 16.8s	remaining: 2m 40s
189:	test: 0.6524758	best: 0.6524826 (188)	total: 16.9s	remaining: 2m 40s
190:	test: 0.6524735	best: 0.6524826 (188)	total: 17s	remaining: 2m 40s
191:	test: 0.6525206	best: 0.6525206 (191)	total: 17.1s	remaining: 2m 40s
192:	test: 0.6525157	best: 0.6525206 (191)	total: 17.1s	remaining: 2m 40s
193:	test: 0.6525908	best: 0.6525908 (193)	total: 17.2s	remaining: 2m 40s
194:	test: 0.6525995	best: 0.6525995 (194)	total: 17.3s	remaining: 2m 39s
195:	test: 0.6526186	best: 0.6526186 (195)	total: 17.3s	remaining: 2m 39s
196:	test: 0.6526807	best: 0.6526807 (196)	total: 17.4s	remaining: 2m 39s
197:	test: 0.6526615	best: 0.6526807 (196)	total: 17.5s	remaining: 2m 39s
198:	test: 0.6526555	best: 0.6526807 (196)	total: 17.6s	remaining: 2m 38s
199:	test: 0.6526702	best: 0.6526807 (196)	total: 17.7s	remaining: 2m 39s
200:	test: 0.6526746	best: 0.6526807 (196)	total: 17.7s	remaining: 2m 38s
201:	test: 0.6526369	best: 0.6526807 (196)	total: 17.9s	remaining: 2m 38s
202:	test: 0.6526248	best: 0.6526807 (196)	total: 17.9s	remaining: 2m 38s
203:	test: 0.6526608	best: 0.6526807 (196)	total: 18s	remaining: 2m 38s
204:	test: 0.6526488	best: 0.6526807 (196)	total: 18s	remaining: 2m 38s
205:	test: 0.6526486	best: 0.6526807 (196)	total: 18.1s	remaining: 2m 37s
206:	test: 0.6527626	best: 0.6527626 (206)	total: 18.2s	remaining: 2m 37s
207:	test: 0.6526921	best: 0.6527626 (206)	total: 18.3s	remaining: 2m 37s
208:	test: 0.6526856	best: 0.6527626 (206)	total: 18.4s	remaining: 2m 37s
209:	test: 0.6526663	best: 0.6527626 (206)	total: 18.5s	remaining: 2m 37s
210:	test: 0.6527521	best: 0.6527626 (206)	total: 18.5s	remaining: 2m 37s
211:	test: 0.6527800	best: 0.6527800 (211)	total: 18.6s	remaining: 2m 36s
212:	test: 0.6527589	best: 0.6527800 (211)	total: 18.7s	remaining: 2m 36s
213:	test: 0.6527609	best: 0.6527800 (211)	total: 18.7s	remaining: 2m 36s
214:	test: 0.6527665	best: 0.6527800 (211)	total: 18.8s	remaining: 2m 36s
215:	test: 0.6527728	best: 0.6527800 (211)	total: 18.9s	remaining: 2m 36s
216:	test: 0.6527643	best: 0.6527800 (211)	total: 19s	remaining: 2m 36s
217:	test: 0.6527793	best: 0.6527800 (211)	total: 19.1s	remaining: 2m 36s
218:	test: 0.6528045	best: 0.6528045 (218)	total: 19.2s	remaining: 2m 36s
219:	test: 0.6528512	best: 0.6528512 (219)	total: 19.3s	remaining: 2m 36s
220:	test: 0.6528185	best: 0.6528512 (219)	total: 19.4s	remaining: 2m 36s
221:	test: 0.6527920	best: 0.6528512 (219)	total: 19.5s	remaining: 2m 36s
222:	test: 0.6528409	best: 0.6528512 (219)	total: 19.6s	remaining: 2m 35s
223:	test: 0.6528417	best: 0.6528512 (219)	total: 19.6s	remaining: 2m 35s
224:	test: 0.6528417	best: 0.6528512 (219)	total: 19.7s	remaining: 2m 35s
225:	test: 0.6527964	best: 0.6528512 (219)	total: 19.7s	remaining: 2m 34s
226:	test: 0.6528390	best: 0.6528512 (219)	total: 19.8s	remaining: 2m 34s
227:	test: 0.6528110	best: 0.6528512 (219)	total: 19.9s	remaining: 2m 34s
228:	test: 0.6527541	best: 0.6528512 (219)	total: 20s	remaining: 2m 34s
229:	test: 0.6527976	best: 0.6528512 (219)	total: 20.1s	remaining: 2m 34s
230:	test: 0.6527424	best: 0.6528512 (219)	total: 20.2s	remaining: 2m 34s
231:	test: 0.6527305	best: 0.6528512 (219)	total: 20.2s	remaining: 2m 34s
232:	test: 0.6527333	best: 0.6528512 (219)	total: 20.3s	remaining: 2m 34s
233:	test: 0.6527538	best: 0.6528512 (219)	total: 20.4s	remaining: 2m 34s
234:	test: 0.6527398	best: 0.6528512 (219)	total: 20.5s	remaining: 2m 34s
235:	test: 0.6527559	best: 0.6528512 (219)	total: 20.6s	remaining: 2m 34s
236:	test: 0.6527326	best: 0.6528512 (219)	total: 20.7s	remaining: 2m 33s
237:	test: 0.6527515	best: 0.6528512 (219)	total: 20.8s	remaining: 2m 33s
238:	test: 0.6527472	best: 0.6528512 (219)	total: 20.8s	remaining: 2m 33s
239:	test: 0.6527119	best: 0.6528512 (219)	total: 20.9s	remaining: 2m 33s
240:	test: 0.6527400	best: 0.6528512 (219)	total: 20.9s	remaining: 2m 32s
241:	test: 0.6527246	best: 0.6528512 (219)	total: 21s	remaining: 2m 32s
242:	test: 0.6527023	best: 0.6528512 (219)	total: 21.1s	remaining: 2m 32s
243:	test: 0.6527127	best: 0.6528512 (219)	total: 21.2s	remaining: 2m 32s
244:	test: 0.6526917	best: 0.6528512 (219)	total: 21.3s	remaining: 2m 32s
245:	test: 0.6527121	best: 0.6528512 (219)	total: 21.4s	remaining: 2m 32s
246:	test: 0.6527357	best: 0.6528512 (219)	total: 21.5s	remaining: 2m 32s
247:	test: 0.6527684	best: 0.6528512 (219)	total: 21.6s	remaining: 2m 32s
248:	test: 0.6527732	best: 0.6528512 (219)	total: 21.6s	remaining: 2m 32s
249:	test: 0.6527659	best: 0.6528512 (219)	total: 21.7s	remaining: 2m 32s
250:	test: 0.6528056	best: 0.6528512 (219)	total: 21.8s	remaining: 2m 32s
251:	test: 0.6526482	best: 0.6528512 (219)	total: 21.9s	remaining: 2m 31s
252:	test: 0.6526211	best: 0.6528512 (219)	total: 22s	remaining: 2m 31s
253:	test: 0.6526211	best: 0.6528512 (219)	total: 22s	remaining: 2m 31s
254:	test: 0.6526408	best: 0.6528512 (219)	total: 22.2s	remaining: 2m 31s
255:	test: 0.6526158	best: 0.6528512 (219)	total: 22.2s	remaining: 2m 31s
256:	test: 0.6525947	best: 0.6528512 (219)	total: 22.3s	remaining: 2m 31s
257:	test: 0.6524942	best: 0.6528512 (219)	total: 22.4s	remaining: 2m 31s
258:	test: 0.6525626	best: 0.6528512 (219)	total: 22.5s	remaining: 2m 31s
259:	test: 0.6525921	best: 0.6528512 (219)	total: 22.6s	remaining: 2m 31s
260:	test: 0.6525869	best: 0.6528512 (219)	total: 22.7s	remaining: 2m 30s
261:	test: 0.6525324	best: 0.6528512 (219)	total: 22.8s	remaining: 2m 31s
262:	test: 0.6525107	best: 0.6528512 (219)	total: 22.8s	remaining: 2m 30s
263:	test: 0.6525482	best: 0.6528512 (219)	total: 22.9s	remaining: 2m 30s
264:	test: 0.6525159	best: 0.6528512 (219)	total: 23s	remaining: 2m 30s
265:	test: 0.6525310	best: 0.6528512 (219)	total: 23.1s	remaining: 2m 30s
266:	test: 0.6525746	best: 0.6528512 (219)	total: 23.2s	remaining: 2m 30s
267:	test: 0.6525762	best: 0.6528512 (219)	total: 23.2s	remaining: 2m 30s
268:	test: 0.6525840	best: 0.6528512 (219)	total: 23.3s	remaining: 2m 30s
269:	test: 0.6526429	best: 0.6528512 (219)	total: 23.4s	remaining: 2m 29s
270:	test: 0.6526324	best: 0.6528512 (219)	total: 23.5s	remaining: 2m 29s
271:	test: 0.6525694	best: 0.6528512 (219)	total: 23.6s	remaining: 2m 29s
272:	test: 0.6525656	best: 0.6528512 (219)	total: 23.7s	remaining: 2m 29s
273:	test: 0.6523359	best: 0.6528512 (219)	total: 23.8s	remaining: 2m 29s

In [118]:
# 4.测试集预测
preds = model.predict_proba(test_data[feature_list])
preds

array([[0.57207427, 0.42792573],
       [0.86148328, 0.13851672],
       [0.52009973, 0.47990027],
       ...,
       [0.46044245, 0.53955755],
       [0.44733027, 0.55266973],
       [0.38687271, 0.61312729]])

In [ ]:
'''
test_data['label'] = preds[:, 1]  # 取正类的概率存储
test_data[['id', 'label']].to_csv('submission.csv', index=False)
'''