In [170]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split  
import pandas as pd
#分块处理大文件
# chunk_iter = pd.read_csv("data/train_data.csv", chunksize=10000)
# chunks = [chunk for chunk in chunk_iter]
# train_data = pd.concat(chunks)
train_data = pd.read_csv("train/train.csv")
test_data = pd.read_csv("testaa/testaa.csv")

train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53480 entries, 0 to 53479
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                53480 non-null  int64
 1   title             53480 non-null  int64
 2   career            50872 non-null  float64
 3   zip_code          53480 non-null  int64
 4   residence         53480 non-null  int64
 5   loan              53480 non-null  int64
 6   term              53480 non-null  int64
 7   interest_rate     53480 non-null  float64
 8   issue_time        53480 non-null  int64
 9   syndicated        53480 non-null  int64
 10  installment       53480 non-null  int64
 11  record_time       53480 non-null  int64
 12  history_time      53480 non-null  int64
 13  total_accounts    53480 non-null  float64
 14  balance_accounts  53480 non-null  float64
 15  balance_limit     53350 non-null  float64
 16  balance           53480 non-null  float64
 17  level             53480 non-null  object
 18  label             53480 non-null  int64
dtypes: float64(6), int64(12), object(1)
memory usage: 7.8+ MB

In [ ]:
###   特征工程
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# 删除zip-code
train_data.drop('zip_code',axis=1, inplace=True)
test_data.drop('zip_code',axis=1, inplace=True)

# 1. 初始自动分离（基于数据类型）
numerical_fea = train_data.select_dtypes(exclude=['object']).columns.tolist()
category_fea = train_data.select_dtypes(include=['object']).columns.tolist()
numerical_fea.remove('label')  # 移除标签列

# 2. 手动调整特定字段类型
features_to_convert = ['title', 'career','residence']  # 需重分类的特征

# 将指定特征从类别型移至数值型
for feature in features_to_convert:
    if feature in category_fea:
        category_fea.remove(feature)
        numerical_fea.append(feature)

# 3. 缺失值处理
# 数值特征：中位数填充 balance_limit
train_data[numerical_fea] = train_data[numerical_fea].fillna(train_data[numerical_fea].median())
test_data[numerical_fea] = test_data[numerical_fea].fillna(test_data[numerical_fea].median())
# 类别特征：众数填充/-1填充 career
train_data[category_fea] = train_data[category_fea].fillna(-1)
test_data[category_fea] = test_data[category_fea].fillna(-1)


# 4. 类别特征编码
def level_to_num(level):
    grade_map = {'A':0, 'B':1, 'C':2, 'D':3, 'E':4}
    grade = level[0]              # A/B/C/D/E
    sub = int(level[1])           # 0-5
    return grade_map[grade] * 6 + sub
train_data['level_num'] = train_data['level'].apply(level_to_num)
test_data['level_num'] = test_data['level'].apply(level_to_num)
train_data.drop('level', axis=1, inplace=True)
test_data.drop('level', axis=1, inplace=True)
numerical_fea.append('level_num')
category_fea.remove('level')

'\n# 5. 数值特征标准化\nscaler = StandardScaler()\ntrain_data[numerical_fea] = scaler.fit_transform(train_data[numerical_fea])\n'

In [172]:
# 对时间进行处理
import datetime
current_time = datetime.datetime.now()  # 或定义一个基准时间
original_time = ['issue_time', 'record_time', 'history_time']
for time_col in original_time:
    train_data[time_col + '_dt'] = pd.to_datetime(train_data[time_col], unit='s')  # Unix秒时间戳
    test_data[time_col + '_dt'] = pd.to_datetime(test_data[time_col], unit='s')
    train_data[time_col + '_age_days'] = (current_time - train_data[time_col + '_dt']).dt.days
    test_data[time_col + '_age_days'] = (current_time - test_data[time_col + '_dt']).dt.days
    numerical_fea.remove(time_col)
    numerical_fea.append(time_col + '_age_days')
    train_data.drop(time_col + '_dt',axis=1, inplace=True)
    test_data.drop(time_col + '_dt',axis=1, inplace=True)


train_data.drop(original_time,axis=1, inplace=True)
test_data.drop(original_time,axis=1, inplace=True)

#cat feature处理
catfeature_list = [col for col in train_data.columns if col != "label"]

In [173]:
def addStatementFeature(df, filepath):
    df_statement = pd.read_csv(filepath)
    
    # 方法1：保留 'id' 并排除 'label'
    cols_to_merge = [col for col in df_statement.columns if col != 'label']  # 保留 'id'
    
    # 方法2：显式添加 'id'（更安全）
    # cols_to_merge = ['id'] + [col for col in df_statement.columns if col not in ['id', 'label']]
    
    # 合并时确保右侧包含 'id'
    merged_df = pd.merge(
        df,
        df_statement[cols_to_merge],  # 此时包含 'id'
        on='id',
        how='left',
        suffixes=('', '_statement')
    )
    return merged_df

train_data = addStatementFeature(train_data,'train/train_statement_feature.csv')
test_data = addStatementFeature(test_data,'testaa/testaa_statement_feature.csv')
'''
catfeature_list.extend(['income_count', 'expense_count', 'big_income_count',
     'negative_balance_count'])
'''
for fea in catfeature_list:
    train_data[fea] = train_data[fea].astype('int64')
    test_data[fea] = test_data[fea].astype('int64')

In [175]:
category_fea

[]

In [176]:
numerical_fea

['id',
 'title',
 'career',
 'residence',
 'loan',
 'term',
 'interest_rate',
 'syndicated',
 'installment',
 'total_accounts',
 'balance_accounts',
 'balance_limit',
 'balance',
 'level_num',
 'issue_time_age_days',
 'record_time_age_days',
 'history_time_age_days']

In [177]:
catfeature_list

['id',
 'title',
 'career',
 'residence',
 'loan',
 'term',
 'interest_rate',
 'syndicated',
 'installment',
 'total_accounts',
 'balance_accounts',
 'balance_limit',
 'balance',
 'level_num',
 'issue_time_age_days',
 'record_time_age_days',
 'history_time_age_days']

In [178]:
train_data.head()

,id,title,career,residence,loan,term,interest_rate,syndicated,installment,total_accounts,...,income_expense_ratio,avg_income,income_std,expense_std,big_income_count,big_income_ratio,min_balance,final_balance,negative_balance_count,negative_balance_ratio
0,0,9,0,1,7200,36,10,0,1,17,...,0.202311,287.607143,269.295352,645.981279,0.0,0.000000,-48391.79,-47628.00,48.0,1.000000
1,1,8,10,0,21300,36,12,0,0,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,8,7,1,10400,60,21,0,0,17,...,2.435264,360.993636,599.383992,86.884890,2.0,0.045455,-951.78,9361.34,4.0,0.083333
3,3,7,2,0,33050,36,16,0,1,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,8,3,1,5200,36,14,0,0,17,...,1.515401,354.288506,556.915876,208.710804,5.0,0.057471,-4481.30,10483.20,39.0,0.419355

In [179]:
from sklearn.model_selection import train_test_split
# 1. 删除id列（正确用法）
train_data.drop('id', axis=1, inplace=True)  # 不赋值，直接修改原对象
catfeature_list.remove('id')
feature_list = [col for col in train_data.columns if col != "label"]
X_train, X_validation, y_train, y_validation = train_test_split(train_data.loc[:, feature_list], train_data.loc[:, 'label'], test_size=0.2 , random_state=2000)

In [180]:
X_train.head()

,title,career,residence,loan,term,interest_rate,syndicated,installment,total_accounts,balance_accounts,...,income_expense_ratio,avg_income,income_std,expense_std,big_income_count,big_income_ratio,min_balance,final_balance,negative_balance_count,negative_balance_ratio
12232,7,10,0,5200,36,9,0,1,41,15,...,0.773732,409.711587,697.243115,402.490795,3.0,0.047619,-7548.34,-7548.34,19.0,0.275362
12974,6,7,0,33050,36,19,0,0,15,8,...,0.438832,370.394231,366.761969,603.304386,0.0,0.000000,-25589.99,-24629.90,56.0,0.982456
47946,1,4,1,11000,12,30,0,0,10,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6185,9,7,1,15350,36,13,0,0,43,17,...,0.838846,336.102632,479.624971,477.597515,3.0,0.039474,-11448.60,-4907.31,81.0,0.987805
29067,0,4,2,9000,12,10,0,0,5,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 3. 模型建立与训练
# 确保 Notebook 内联显示图形
%matplotlib inline 
from catboost import CatBoostClassifier

model = CatBoostClassifier(iterations=2000,
                           #task_type='GPU',
                           #bootstrap_type='Poisson',
                           task_type='CPU',
                           cat_features=catfeature_list,
                           eval_metric='AUC',
                           logging_level='Verbose',
                           learning_rate=0.03,
                           depth=6, 
                           l2_leaf_reg=5,
                           loss_function='Logloss',
                            early_stopping_rounds=300,
                           scale_pos_weight=(len(y_train[y_train==0])/len(y_train[y_train == 1])),
                            random_seed= 42
                           )
model.fit(X_train.loc[:, feature_list], y_train, 
          eval_set=(X_validation.loc[:, feature_list], y_validation), plot=True)

plt.show()

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	test: 0.6258169	best: 0.6258169 (0)	total: 163ms	remaining: 5m 25s
1:	test: 0.6363709	best: 0.6363709 (1)	total: 272ms	remaining: 4m 31s
2:	test: 0.6396401	best: 0.6396401 (2)	total: 417ms	remaining: 4m 37s
3:	test: 0.6414251	best: 0.6414251 (3)	total: 517ms	remaining: 4m 18s
4:	test: 0.6404479	best: 0.6414251 (3)	total: 623ms	remaining: 4m 8s
5:	test: 0.6428357	best: 0.6428357 (5)	total: 706ms	remaining: 3m 54s
6:	test: 0.6427970	best: 0.6428357 (5)	total: 765ms	remaining: 3m 37s
7:	test: 0.6445256	best: 0.6445256 (7)	total: 839ms	remaining: 3m 29s
8:	test: 0.6447654	best: 0.6447654 (8)	total: 914ms	remaining: 3m 22s
9:	test: 0.6466274	best: 0.6466274 (9)	total: 995ms	remaining: 3m 17s
10:	test: 0.6466982	best: 0.6466982 (10)	total: 1.06s	remaining: 3m 12s
11:	test: 0.6459309	best: 0.6466982 (10)	total: 1.14s	remaining: 3m 8s
12:	test: 0.6463949	best: 0.6466982 (10)	total: 1.23s	remaining: 3m 7s
13:	test: 0.6464098	best: 0.6466982 (10)	total: 1.29s	remaining: 3m 3s
14:	test: 0.6465951	best: 0.6466982 (10)	total: 1.35s	remaining: 2m 58s
15:	test: 0.6468547	best: 0.6468547 (15)	total: 1.42s	remaining: 2m 55s
16:	test: 0.6460434	best: 0.6468547 (15)	total: 1.46s	remaining: 2m 50s
17:	test: 0.6459542	best: 0.6468547 (15)	total: 1.54s	remaining: 2m 49s
18:	test: 0.6459906	best: 0.6468547 (15)	total: 1.59s	remaining: 2m 45s
19:	test: 0.6462202	best: 0.6468547 (15)	total: 1.66s	remaining: 2m 44s
20:	test: 0.6459721	best: 0.6468547 (15)	total: 1.71s	remaining: 2m 41s
21:	test: 0.6451290	best: 0.6468547 (15)	total: 1.8s	remaining: 2m 41s
22:	test: 0.6450825	best: 0.6468547 (15)	total: 1.86s	remaining: 2m 40s
23:	test: 0.6452501	best: 0.6468547 (15)	total: 1.93s	remaining: 2m 39s
24:	test: 0.6452782	best: 0.6468547 (15)	total: 2.02s	remaining: 2m 39s
25:	test: 0.6451202	best: 0.6468547 (15)	total: 2.08s	remaining: 2m 38s
26:	test: 0.6459416	best: 0.6468547 (15)	total: 2.23s	remaining: 2m 43s
27:	test: 0.6455941	best: 0.6468547 (15)	total: 2.3s	remaining: 2m 41s
28:	test: 0.6455076	best: 0.6468547 (15)	total: 2.38s	remaining: 2m 41s
29:	test: 0.6455174	best: 0.6468547 (15)	total: 2.45s	remaining: 2m 40s
30:	test: 0.6459628	best: 0.6468547 (15)	total: 2.52s	remaining: 2m 40s
31:	test: 0.6458910	best: 0.6468547 (15)	total: 2.79s	remaining: 2m 51s
32:	test: 0.6459485	best: 0.6468547 (15)	total: 3.21s	remaining: 3m 11s
33:	test: 0.6454032	best: 0.6468547 (15)	total: 3.35s	remaining: 3m 13s
34:	test: 0.6466017	best: 0.6468547 (15)	total: 3.47s	remaining: 3m 14s
35:	test: 0.6466403	best: 0.6468547 (15)	total: 3.55s	remaining: 3m 13s
36:	test: 0.6464141	best: 0.6468547 (15)	total: 3.64s	remaining: 3m 13s
37:	test: 0.6473375	best: 0.6473375 (37)	total: 3.73s	remaining: 3m 12s
38:	test: 0.6474855	best: 0.6474855 (38)	total: 3.79s	remaining: 3m 10s
39:	test: 0.6474728	best: 0.6474855 (38)	total: 3.85s	remaining: 3m 8s
40:	test: 0.6492948	best: 0.6492948 (40)	total: 3.93s	remaining: 3m 7s
41:	test: 0.6493531	best: 0.6493531 (41)	total: 4s	remaining: 3m 6s
42:	test: 0.6495199	best: 0.6495199 (42)	total: 4.07s	remaining: 3m 5s
43:	test: 0.6498705	best: 0.6498705 (43)	total: 4.14s	remaining: 3m 4s
44:	test: 0.6500875	best: 0.6500875 (44)	total: 4.22s	remaining: 3m 3s
45:	test: 0.6504605	best: 0.6504605 (45)	total: 4.29s	remaining: 3m 2s
46:	test: 0.6505335	best: 0.6505335 (46)	total: 4.38s	remaining: 3m 1s
47:	test: 0.6520531	best: 0.6520531 (47)	total: 4.69s	remaining: 3m 10s
48:	test: 0.6535086	best: 0.6535086 (48)	total: 4.79s	remaining: 3m 10s
49:	test: 0.6537605	best: 0.6537605 (49)	total: 4.87s	remaining: 3m 10s
50:	test: 0.6542835	best: 0.6542835 (50)	total: 4.96s	remaining: 3m 9s
51:	test: 0.6545367	best: 0.6545367 (51)	total: 5.04s	remaining: 3m 8s
52:	test: 0.6546354	best: 0.6546354 (52)	total: 5.29s	remaining: 3m 14s
53:	test: 0.6555124	best: 0.6555124 (53)	total: 5.4s	remaining: 3m 14s
54:	test: 0.6556018	best: 0.6556018 (54)	total: 5.51s	remaining: 3m 14s
55:	test: 0.6557926	best: 0.6557926 (55)	total: 5.61s	remaining: 3m 14s
56:	test: 0.6560403	best: 0.6560403 (56)	total: 5.68s	remaining: 3m 13s
57:	test: 0.6561553	best: 0.6561553 (57)	total: 5.85s	remaining: 3m 15s
58:	test: 0.6571352	best: 0.6571352 (58)	total: 6.07s	remaining: 3m 19s
59:	test: 0.6573219	best: 0.6573219 (59)	total: 6.17s	remaining: 3m 19s
60:	test: 0.6570370	best: 0.6573219 (59)	total: 6.24s	remaining: 3m 18s
61:	test: 0.6572092	best: 0.6573219 (59)	total: 6.32s	remaining: 3m 17s
62:	test: 0.6575972	best: 0.6575972 (62)	total: 6.45s	remaining: 3m 18s
63:	test: 0.6583576	best: 0.6583576 (63)	total: 6.72s	remaining: 3m 23s
64:	test: 0.6588180	best: 0.6588180 (64)	total: 6.91s	remaining: 3m 25s
65:	test: 0.6586419	best: 0.6588180 (64)	total: 7s	remaining: 3m 25s
66:	test: 0.6594448	best: 0.6594448 (66)	total: 7.08s	remaining: 3m 24s
67:	test: 0.6599149	best: 0.6599149 (67)	total: 7.17s	remaining: 3m 23s
68:	test: 0.6600468	best: 0.6600468 (68)	total: 7.29s	remaining: 3m 23s
69:	test: 0.6603101	best: 0.6603101 (69)	total: 7.56s	remaining: 3m 28s
70:	test: 0.6604745	best: 0.6604745 (70)	total: 7.64s	remaining: 3m 27s
71:	test: 0.6611008	best: 0.6611008 (71)	total: 7.73s	remaining: 3m 26s
72:	test: 0.6616434	best: 0.6616434 (72)	total: 7.84s	remaining: 3m 27s
73:	test: 0.6615675	best: 0.6616434 (72)	total: 7.95s	remaining: 3m 26s
74:	test: 0.6618096	best: 0.6618096 (74)	total: 8.04s	remaining: 3m 26s
75:	test: 0.6622069	best: 0.6622069 (75)	total: 8.13s	remaining: 3m 25s
76:	test: 0.6625544	best: 0.6625544 (76)	total: 8.22s	remaining: 3m 25s
77:	test: 0.6627796	best: 0.6627796 (77)	total: 8.31s	remaining: 3m 24s
78:	test: 0.6629452	best: 0.6629452 (78)	total: 8.42s	remaining: 3m 24s
79:	test: 0.6628799	best: 0.6629452 (78)	total: 8.51s	remaining: 3m 24s
80:	test: 0.6633853	best: 0.6633853 (80)	total: 8.61s	remaining: 3m 23s
81:	test: 0.6637275	best: 0.6637275 (81)	total: 8.69s	remaining: 3m 23s
82:	test: 0.6638187	best: 0.6638187 (82)	total: 8.77s	remaining: 3m 22s
83:	test: 0.6637022	best: 0.6638187 (82)	total: 8.88s	remaining: 3m 22s
84:	test: 0.6640487	best: 0.6640487 (84)	total: 8.96s	remaining: 3m 21s
85:	test: 0.6642029	best: 0.6642029 (85)	total: 9.01s	remaining: 3m 20s
86:	test: 0.6641669	best: 0.6642029 (85)	total: 9.09s	remaining: 3m 19s
87:	test: 0.6646090	best: 0.6646090 (87)	total: 9.17s	remaining: 3m 19s
88:	test: 0.6650207	best: 0.6650207 (88)	total: 9.26s	remaining: 3m 18s
89:	test: 0.6651519	best: 0.6651519 (89)	total: 9.29s	remaining: 3m 17s
90:	test: 0.6650920	best: 0.6651519 (89)	total: 9.37s	remaining: 3m 16s
91:	test: 0.6650794	best: 0.6651519 (89)	total: 9.46s	remaining: 3m 16s
92:	test: 0.6650887	best: 0.6651519 (89)	total: 9.54s	remaining: 3m 15s
93:	test: 0.6651206	best: 0.6651519 (89)	total: 9.62s	remaining: 3m 15s
94:	test: 0.6650574	best: 0.6651519 (89)	total: 9.7s	remaining: 3m 14s
95:	test: 0.6650082	best: 0.6651519 (89)	total: 9.77s	remaining: 3m 13s
96:	test: 0.6649103	best: 0.6651519 (89)	total: 9.85s	remaining: 3m 13s
97:	test: 0.6652739	best: 0.6652739 (97)	total: 9.94s	remaining: 3m 12s
98:	test: 0.6654553	best: 0.6654553 (98)	total: 10s	remaining: 3m 12s
99:	test: 0.6656005	best: 0.6656005 (99)	total: 10.1s	remaining: 3m 12s
100:	test: 0.6655318	best: 0.6656005 (99)	total: 10.3s	remaining: 3m 13s
101:	test: 0.6656687	best: 0.6656687 (101)	total: 10.4s	remaining: 3m 12s
102:	test: 0.6657138	best: 0.6657138 (102)	total: 10.4s	remaining: 3m 12s
103:	test: 0.6657799	best: 0.6657799 (103)	total: 10.5s	remaining: 3m 11s
104:	test: 0.6659926	best: 0.6659926 (104)	total: 10.6s	remaining: 3m 11s
105:	test: 0.6659760	best: 0.6659926 (104)	total: 10.9s	remaining: 3m 15s
106:	test: 0.6660603	best: 0.6660603 (106)	total: 11s	remaining: 3m 14s
107:	test: 0.6661636	best: 0.6661636 (107)	total: 11.1s	remaining: 3m 14s
108:	test: 0.6662655	best: 0.6662655 (108)	total: 11.2s	remaining: 3m 13s
109:	test: 0.6662643	best: 0.6662655 (108)	total: 11.2s	remaining: 3m 12s
110:	test: 0.6662242	best: 0.6662655 (108)	total: 11.3s	remaining: 3m 11s
111:	test: 0.6664365	best: 0.6664365 (111)	total: 11.4s	remaining: 3m 11s
112:	test: 0.6663655	best: 0.6664365 (111)	total: 11.4s	remaining: 3m 11s
113:	test: 0.6664374	best: 0.6664374 (113)	total: 11.5s	remaining: 3m 10s
114:	test: 0.6664660	best: 0.6664660 (114)	total: 11.6s	remaining: 3m 10s
115:	test: 0.6665192	best: 0.6665192 (115)	total: 11.6s	remaining: 3m 8s
116:	test: 0.6664686	best: 0.6665192 (115)	total: 11.7s	remaining: 3m 8s
117:	test: 0.6666201	best: 0.6666201 (117)	total: 11.8s	remaining: 3m 7s
118:	test: 0.6665997	best: 0.6666201 (117)	total: 11.8s	remaining: 3m 6s
119:	test: 0.6666171	best: 0.6666201 (117)	total: 11.9s	remaining: 3m 6s
120:	test: 0.6667857	best: 0.6667857 (120)	total: 12s	remaining: 3m 5s
121:	test: 0.6668010	best: 0.6668010 (121)	total: 12s	remaining: 3m 5s
122:	test: 0.6668782	best: 0.6668782 (122)	total: 12.1s	remaining: 3m 5s
123:	test: 0.6668813	best: 0.6668813 (123)	total: 12.2s	remaining: 3m 4s
124:	test: 0.6669951	best: 0.6669951 (124)	total: 12.3s	remaining: 3m 4s
125:	test: 0.6670139	best: 0.6670139 (125)	total: 12.4s	remaining: 3m 4s
126:	test: 0.6669920	best: 0.6670139 (125)	total: 12.5s	remaining: 3m 4s
127:	test: 0.6670497	best: 0.6670497 (127)	total: 12.5s	remaining: 3m 3s
128:	test: 0.6670858	best: 0.6670858 (128)	total: 12.6s	remaining: 3m 2s
129:	test: 0.6671699	best: 0.6671699 (129)	total: 12.7s	remaining: 3m 2s
130:	test: 0.6670960	best: 0.6671699 (129)	total: 12.8s	remaining: 3m 1s
131:	test: 0.6670571	best: 0.6671699 (129)	total: 12.8s	remaining: 3m 1s
132:	test: 0.6670559	best: 0.6671699 (129)	total: 12.9s	remaining: 3m 1s
133:	test: 0.6672080	best: 0.6672080 (133)	total: 13s	remaining: 3m 1s
134:	test: 0.6672216	best: 0.6672216 (134)	total: 13.1s	remaining: 3m
135:	test: 0.6672159	best: 0.6672216 (134)	total: 13.2s	remaining: 3m
136:	test: 0.6671807	best: 0.6672216 (134)	total: 13.2s	remaining: 2m 59s
137:	test: 0.6672201	best: 0.6672216 (134)	total: 13.3s	remaining: 2m 59s
138:	test: 0.6671744	best: 0.6672216 (134)	total: 13.4s	remaining: 2m 59s
139:	test: 0.6671654	best: 0.6672216 (134)	total: 13.5s	remaining: 2m 58s
140:	test: 0.6672746	best: 0.6672746 (140)	total: 13.5s	remaining: 2m 58s
141:	test: 0.6672610	best: 0.6672746 (140)	total: 13.6s	remaining: 2m 57s
142:	test: 0.6673878	best: 0.6673878 (142)	total: 13.7s	remaining: 2m 57s
143:	test: 0.6673914	best: 0.6673914 (143)	total: 13.8s	remaining: 2m 57s
144:	test: 0.6673448	best: 0.6673914 (143)	total: 13.8s	remaining: 2m 57s
145:	test: 0.6673329	best: 0.6673914 (143)	total: 13.9s	remaining: 2m 56s
146:	test: 0.6673600	best: 0.6673914 (143)	total: 14s	remaining: 2m 56s
147:	test: 0.6673559	best: 0.6673914 (143)	total: 14s	remaining: 2m 55s
148:	test: 0.6673611	best: 0.6673914 (143)	total: 14.1s	remaining: 2m 55s
149:	test: 0.6673130	best: 0.6673914 (143)	total: 14.2s	remaining: 2m 55s
150:	test: 0.6673084	best: 0.6673914 (143)	total: 14.3s	remaining: 2m 55s
151:	test: 0.6673471	best: 0.6673914 (143)	total: 14.4s	remaining: 2m 54s
152:	test: 0.6673197	best: 0.6673914 (143)	total: 14.5s	remaining: 2m 54s
153:	test: 0.6673037	best: 0.6673914 (143)	total: 14.6s	remaining: 2m 54s
154:	test: 0.6673602	best: 0.6673914 (143)	total: 14.7s	remaining: 2m 54s
155:	test: 0.6673954	best: 0.6673954 (155)	total: 14.9s	remaining: 2m 56s
156:	test: 0.6674396	best: 0.6674396 (156)	total: 15s	remaining: 2m 56s
157:	test: 0.6674870	best: 0.6674870 (157)	total: 15.1s	remaining: 2m 56s
158:	test: 0.6675551	best: 0.6675551 (158)	total: 15.2s	remaining: 2m 56s
159:	test: 0.6675964	best: 0.6675964 (159)	total: 15.3s	remaining: 2m 55s
160:	test: 0.6676425	best: 0.6676425 (160)	total: 15.4s	remaining: 2m 55s
161:	test: 0.6676805	best: 0.6676805 (161)	total: 15.5s	remaining: 2m 55s
162:	test: 0.6676716	best: 0.6676805 (161)	total: 15.5s	remaining: 2m 55s
163:	test: 0.6676078	best: 0.6676805 (161)	total: 15.7s	remaining: 2m 55s
164:	test: 0.6677075	best: 0.6677075 (164)	total: 15.8s	remaining: 2m 55s
165:	test: 0.6677575	best: 0.6677575 (165)	total: 15.8s	remaining: 2m 55s
166:	test: 0.6678061	best: 0.6678061 (166)	total: 15.9s	remaining: 2m 55s
167:	test: 0.6677768	best: 0.6678061 (166)	total: 16s	remaining: 2m 54s
168:	test: 0.6678226	best: 0.6678226 (168)	total: 16.1s	remaining: 2m 54s
169:	test: 0.6678071	best: 0.6678226 (168)	total: 16.2s	remaining: 2m 54s
170:	test: 0.6677738	best: 0.6678226 (168)	total: 16.3s	remaining: 2m 54s
171:	test: 0.6677968	best: 0.6678226 (168)	total: 16.4s	remaining: 2m 54s
172:	test: 0.6678764	best: 0.6678764 (172)	total: 16.5s	remaining: 2m 54s
173:	test: 0.6678455	best: 0.6678764 (172)	total: 16.6s	remaining: 2m 54s
174:	test: 0.6678494	best: 0.6678764 (172)	total: 16.7s	remaining: 2m 53s
175:	test: 0.6678508	best: 0.6678764 (172)	total: 16.8s	remaining: 2m 53s
176:	test: 0.6678527	best: 0.6678764 (172)	total: 16.8s	remaining: 2m 53s
177:	test: 0.6678344	best: 0.6678764 (172)	total: 16.9s	remaining: 2m 52s
178:	test: 0.6678250	best: 0.6678764 (172)	total: 17s	remaining: 2m 52s
179:	test: 0.6678232	best: 0.6678764 (172)	total: 17.1s	remaining: 2m 52s
180:	test: 0.6678227	best: 0.6678764 (172)	total: 17.2s	remaining: 2m 52s
181:	test: 0.6678161	best: 0.6678764 (172)	total: 17.3s	remaining: 2m 52s
182:	test: 0.6678524	best: 0.6678764 (172)	total: 17.4s	remaining: 2m 52s
183:	test: 0.6678760	best: 0.6678764 (172)	total: 17.4s	remaining: 2m 52s
184:	test: 0.6679755	best: 0.6679755 (184)	total: 17.5s	remaining: 2m 51s
185:	test: 0.6679644	best: 0.6679755 (184)	total: 17.6s	remaining: 2m 51s
186:	test: 0.6679005	best: 0.6679755 (184)	total: 17.7s	remaining: 2m 51s
187:	test: 0.6679848	best: 0.6679848 (187)	total: 17.8s	remaining: 2m 51s
188:	test: 0.6679848	best: 0.6679848 (187)	total: 17.8s	remaining: 2m 50s
189:	test: 0.6679856	best: 0.6679856 (189)	total: 17.9s	remaining: 2m 50s
190:	test: 0.6679447	best: 0.6679856 (189)	total: 18s	remaining: 2m 50s
191:	test: 0.6679241	best: 0.6679856 (189)	total: 18s	remaining: 2m 49s
192:	test: 0.6679250	best: 0.6679856 (189)	total: 18.1s	remaining: 2m 49s
193:	test: 0.6679114	best: 0.6679856 (189)	total: 18.2s	remaining: 2m 49s
194:	test: 0.6678937	best: 0.6679856 (189)	total: 18.3s	remaining: 2m 48s
195:	test: 0.6679703	best: 0.6679856 (189)	total: 18.3s	remaining: 2m 48s
196:	test: 0.6679906	best: 0.6679906 (196)	total: 18.4s	remaining: 2m 48s
197:	test: 0.6679577	best: 0.6679906 (196)	total: 18.5s	remaining: 2m 48s
198:	test: 0.6679500	best: 0.6679906 (196)	total: 18.6s	remaining: 2m 48s
199:	test: 0.6680065	best: 0.6680065 (199)	total: 18.7s	remaining: 2m 48s
200:	test: 0.6680281	best: 0.6680281 (200)	total: 18.8s	remaining: 2m 48s
201:	test: 0.6679943	best: 0.6680281 (200)	total: 18.9s	remaining: 2m 47s
202:	test: 0.6679950	best: 0.6680281 (200)	total: 19s	remaining: 2m 47s
203:	test: 0.6679387	best: 0.6680281 (200)	total: 19.1s	remaining: 2m 47s
204:	test: 0.6679757	best: 0.6680281 (200)	total: 19.1s	remaining: 2m 47s
205:	test: 0.6679664	best: 0.6680281 (200)	total: 19.2s	remaining: 2m 47s
206:	test: 0.6679258	best: 0.6680281 (200)	total: 19.3s	remaining: 2m 47s
207:	test: 0.6678947	best: 0.6680281 (200)	total: 19.4s	remaining: 2m 47s
208:	test: 0.6679311	best: 0.6680281 (200)	total: 19.5s	remaining: 2m 47s
209:	test: 0.6679707	best: 0.6680281 (200)	total: 19.6s	remaining: 2m 47s
210:	test: 0.6679469	best: 0.6680281 (200)	total: 19.7s	remaining: 2m 46s
211:	test: 0.6679232	best: 0.6680281 (200)	total: 19.8s	remaining: 2m 46s
212:	test: 0.6679931	best: 0.6680281 (200)	total: 19.9s	remaining: 2m 46s
213:	test: 0.6681155	best: 0.6681155 (213)	total: 19.9s	remaining: 2m 46s
214:	test: 0.6681687	best: 0.6681687 (214)	total: 20s	remaining: 2m 46s
215:	test: 0.6682116	best: 0.6682116 (215)	total: 20.1s	remaining: 2m 46s
216:	test: 0.6683697	best: 0.6683697 (216)	total: 20.2s	remaining: 2m 45s
217:	test: 0.6683676	best: 0.6683697 (216)	total: 20.3s	remaining: 2m 45s
218:	test: 0.6683904	best: 0.6683904 (218)	total: 20.3s	remaining: 2m 45s
219:	test: 0.6684015	best: 0.6684015 (219)	total: 20.5s	remaining: 2m 45s
220:	test: 0.6684460	best: 0.6684460 (220)	total: 20.6s	remaining: 2m 45s
221:	test: 0.6684769	best: 0.6684769 (221)	total: 20.6s	remaining: 2m 45s
222:	test: 0.6684856	best: 0.6684856 (222)	total: 20.7s	remaining: 2m 45s
223:	test: 0.6684863	best: 0.6684863 (223)	total: 20.8s	remaining: 2m 44s
224:	test: 0.6686186	best: 0.6686186 (224)	total: 20.9s	remaining: 2m 44s
225:	test: 0.6686335	best: 0.6686335 (225)	total: 21s	remaining: 2m 44s
226:	test: 0.6686198	best: 0.6686335 (225)	total: 21.1s	remaining: 2m 44s
227:	test: 0.6686204	best: 0.6686335 (225)	total: 21.1s	remaining: 2m 44s
228:	test: 0.6686557	best: 0.6686557 (228)	total: 21.2s	remaining: 2m 44s
229:	test: 0.6686434	best: 0.6686557 (228)	total: 21.4s	remaining: 2m 44s
230:	test: 0.6686105	best: 0.6686557 (228)	total: 21.5s	remaining: 2m 44s
231:	test: 0.6686109	best: 0.6686557 (228)	total: 21.6s	remaining: 2m 44s
232:	test: 0.6686572	best: 0.6686572 (232)	total: 21.7s	remaining: 2m 44s
233:	test: 0.6687300	best: 0.6687300 (233)	total: 21.8s	remaining: 2m 44s
234:	test: 0.6687012	best: 0.6687300 (233)	total: 21.9s	remaining: 2m 44s
235:	test: 0.6686982	best: 0.6687300 (233)	total: 22s	remaining: 2m 44s
236:	test: 0.6686794	best: 0.6687300 (233)	total: 22s	remaining: 2m 43s
237:	test: 0.6687652	best: 0.6687652 (237)	total: 22.1s	remaining: 2m 43s
238:	test: 0.6687348	best: 0.6687652 (237)	total: 22.2s	remaining: 2m 43s
239:	test: 0.6686849	best: 0.6687652 (237)	total: 22.3s	remaining: 2m 43s
240:	test: 0.6686421	best: 0.6687652 (237)	total: 22.3s	remaining: 2m 43s
241:	test: 0.6687963	best: 0.6687963 (241)	total: 22.4s	remaining: 2m 43s
242:	test: 0.6688007	best: 0.6688007 (242)	total: 22.5s	remaining: 2m 42s
243:	test: 0.6688491	best: 0.6688491 (243)	total: 22.6s	remaining: 2m 42s
244:	test: 0.6688412	best: 0.6688491 (243)	total: 22.7s	remaining: 2m 42s
245:	test: 0.6688418	best: 0.6688491 (243)	total: 22.8s	remaining: 2m 42s
246:	test: 0.6688390	best: 0.6688491 (243)	total: 22.9s	remaining: 2m 42s
247:	test: 0.6688203	best: 0.6688491 (243)	total: 23s	remaining: 2m 42s
248:	test: 0.6687852	best: 0.6688491 (243)	total: 23s	remaining: 2m 42s
249:	test: 0.6687742	best: 0.6688491 (243)	total: 23.1s	remaining: 2m 41s
250:	test: 0.6688248	best: 0.6688491 (243)	total: 23.2s	remaining: 2m 41s
251:	test: 0.6688092	best: 0.6688491 (243)	total: 23.3s	remaining: 2m 41s
252:	test: 0.6688303	best: 0.6688491 (243)	total: 23.4s	remaining: 2m 41s
253:	test: 0.6688204	best: 0.6688491 (243)	total: 23.5s	remaining: 2m 41s
254:	test: 0.6688173	best: 0.6688491 (243)	total: 23.5s	remaining: 2m 41s
255:	test: 0.6688116	best: 0.6688491 (243)	total: 23.6s	remaining: 2m 40s
256:	test: 0.6688669	best: 0.6688669 (256)	total: 23.7s	remaining: 2m 40s
257:	test: 0.6689238	best: 0.6689238 (257)	total: 23.7s	remaining: 2m 40s
258:	test: 0.6689054	best: 0.6689238 (257)	total: 23.8s	remaining: 2m 40s
259:	test: 0.6689218	best: 0.6689238 (257)	total: 23.9s	remaining: 2m 40s
260:	test: 0.6689227	best: 0.6689238 (257)	total: 24s	remaining: 2m 40s
261:	test: 0.6689264	best: 0.6689264 (261)	total: 24.1s	remaining: 2m 39s
262:	test: 0.6690000	best: 0.6690000 (262)	total: 24.2s	remaining: 2m 39s
263:	test: 0.6690020	best: 0.6690020 (263)	total: 24.2s	remaining: 2m 39s
264:	test: 0.6689988	best: 0.6690020 (263)	total: 24.3s	remaining: 2m 39s
265:	test: 0.6690136	best: 0.6690136 (265)	total: 24.4s	remaining: 2m 39s
266:	test: 0.6690292	best: 0.6690292 (266)	total: 24.5s	remaining: 2m 39s
267:	test: 0.6690720	best: 0.6690720 (267)	total: 24.6s	remaining: 2m 38s
268:	test: 0.6690625	best: 0.6690720 (267)	total: 24.7s	remaining: 2m 38s
269:	test: 0.6690664	best: 0.6690720 (267)	total: 24.7s	remaining: 2m 38s
270:	test: 0.6690507	best: 0.6690720 (267)	total: 24.8s	remaining: 2m 38s
271:	test: 0.6691569	best: 0.6691569 (271)	total: 24.9s	remaining: 2m 37s
272:	test: 0.6691652	best: 0.6691652 (272)	total: 24.9s	remaining: 2m 37s
273:	test: 0.6692015	best: 0.6692015 (273)	total: 25s	remaining: 2m 37s

In [ ]:
# 4.测试集预测
preds = model.predict_proba(test_data[feature_list])
preds

array([[0.74520002, 0.25479998],
       [0.88054788, 0.11945212],
       [0.59113652, 0.40886348],
       ...,
       [0.47910983, 0.52089017],
       [0.48435385, 0.51564615],
       [0.33375663, 0.66624337]])

In [187]:

test_data['label'] = preds[:, 1]  # 取正类的概率存储
test_data[['id', 'label']].to_csv('submission.csv', index=False)